Traceback (most recent call last):
  File "/home/karsten/Modularity/tools/depchase/depchase", line 495, in <module>
    cli(obj={})
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/karsten/Modularity/tools/depchase/depchase", line 469, in resolve
    binary, source = solve(solver, pkgnames, selfhost=selfhost)
  File "/home/karsten/Modularity/tools/depchase/depchase", line 363, in solve
    assert not problems
AssertionError
